// <auto-generated />
using System;
using EOQuoter.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EOQuoter.Data.Migrations.Tracking
{
    [DbContext(typeof(ExecutionTrackingDbContext))]
    partial class ExecutionTrackingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EOQuoter.Data.Entities.SprocExecutionLogRow", b =>
                {
                    b.Property<Guid>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("run_id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("batch_id");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ended_at");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error");

                    b.Property<string>("Params")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("params");

                    b.Property<Guid?>("RejectsRef")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("rejects_ref");

                    b.Property<long>("RowsAffected")
                        .HasColumnType("bigint")
                        .HasColumnName("rows_affected");

                    b.Property<string>("SprocName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("sproc_name");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("RunId")
                        .HasName("pk_sproc_executions");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_sproc_executions_batch_id");

                    b.ToTable("sproc_executions");
                });
#pragma warning restore 612, 618
        }
    }
}
