// <auto-generated />
using System;
using EOQuoter.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EOQuoter.Data.Migrations.Quoter
{
    [DbContext(typeof(QuoterDbContext))]
    partial class QuoterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EOQuoter.Data.Entities.AppetiteRow", b =>
                {
                    b.Property<int>("ProfessionClass")
                        .HasColumnType("int")
                        .HasColumnName("profession_class");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<bool>("IsWritten")
                        .HasColumnType("bit")
                        .HasColumnName("is_written");

                    b.HasKey("ProfessionClass", "EffectiveDate")
                        .HasName("pk_appetite");

                    b.ToTable("appetite");
                });

            modelBuilder.Entity("EOQuoter.Data.Entities.AuditEventRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DetailJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detail_json");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("entity_type");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("event_type");

                    b.Property<string>("ExternalReferenceId")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("external_reference_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("occurred_at");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("EntityId")
                        .HasDatabaseName("ix_audit_events_entity_id");

                    b.HasIndex("ExternalReferenceId")
                        .HasDatabaseName("ix_audit_events_external_reference_id");

                    b.ToTable("audit_events");
                });

            modelBuilder.Entity("EOQuoter.Data.Entities.AuthorityRow", b =>
                {
                    b.Property<string>("State")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("state");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<decimal>("MaxLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("max_limit");

                    b.HasKey("State", "EffectiveDate")
                        .HasName("pk_delegated_authority");

                    b.ToTable("delegated_authority");
                });

            modelBuilder.Entity("EOQuoter.Data.Entities.BatchJobRow", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("job_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int")
                        .HasColumnName("attempt_count");

                    b.Property<string>("Checkpoint")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("checkpoint");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("LastError")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_error");

                    b.Property<DateOnly>("Period")
                        .HasColumnType("date")
                        .HasColumnName("period");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("JobId")
                        .HasName("pk_batch_jobs");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_batch_jobs_status");

                    b.ToTable("batch_jobs");
                });

            modelBuilder.Entity("EOQuoter.Data.Entities.BordereauEntryRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("batch_id");

                    b.Property<decimal>("Commission")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("commission");

                    b.Property<string>("ExternalReferenceId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("external_reference_id");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("generated_at");

                    b.Property<decimal>("GrossPremium")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gross_premium");

                    b.Property<decimal>("NetToCarrier")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("net_to_carrier");

                    b.Property<DateOnly>("Period")
                        .HasColumnType("date")
                        .HasColumnName("period");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("policy_number");

                    b.HasKey("Id")
                        .HasName("pk_bordereau_entries");

                    b.HasIndex("Period", "ExternalReferenceId")
                        .IsUnique()
                        .HasDatabaseName("ix_bordereau_entries_period_external_reference_id");

                    b.ToTable("bordereau_entries");
                });

            modelBuilder.Entity("EOQuoter.Data.Entities.CarrierStatementRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ExternalReferenceId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("external_reference_id");

                    b.Property<decimal>("GrossPremium")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gross_premium");

                    b.Property<DateOnly>("Period")
                        .HasColumnType("date")
                        .HasColumnName("period");

                    b.Property<string>("PolicyNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("policy_number");

                    b.HasKey("Id")
                        .HasName("pk_carrier_statements");

                    b.HasIndex("Period", "ExternalReferenceId")
                        .IsUnique()
                        .HasDatabaseName("ix_carrier_statements_period_external_reference_id");

                    b.ToTable("carrier_statements");
                });

            modelBuilder.Entity("EOQuoter.Data.Entities.DeadLetterRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("DeadLetteredAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dead_lettered_at");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("dedupe_key");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error");

                    b.Property<Guid>("OutboxId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("outbox_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_dead_letters");

                    b.ToTable("dead_letters");
                });

            modelBuilder.Entity("EOQuoter.Data.Entities.IdempotencyRow", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("request_fingerprint");

                    b.Property<string>("ResponseSnapshot")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_snapshot");

                    b.Property<Guid?>("ResultId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("result_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int")
                        .HasColumnName("status_code");

                    b.HasKey("Key")
                        .HasName("pk_idempotency_records");

                    b.ToTable("idempotency_records");
                });

            modelBuilder.Entity("EOQuoter.Data.Entities.LimitFactorRow", b =>
                {
                    b.Property<decimal>("LimitAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("limit_amount");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<decimal>("Factor")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("factor");

                    b.HasKey("LimitAmount", "EffectiveDate")
                        .HasName("pk_limit_factors");

                    b.ToTable("limit_factors");
                });

            modelBuilder.Entity("EOQuoter.Data.Entities.OutboxRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("dedupe_key");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dispatched_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox");

                    b.HasIndex("DispatchedAt")
                        .HasDatabaseName("ix_outbox_dispatched_at");

                    b.HasIndex("Seq")
                        .HasDatabaseName("ix_outbox_seq");

                    b.ToTable("outbox");
                });

            modelBuilder.Entity("EOQuoter.Data.Entities.PolicyRow", b =>
                {
                    b.Property<Guid>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("policy_id");

                    b.Property<DateTimeOffset>("BoundAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("bound_at");

                    b.Property<decimal>("CommissionRate")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("commission_rate");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<string>("ExternalReferenceId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("external_reference_id");

                    b.Property<string>("FormsJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("forms_json");

                    b.Property<DateTimeOffset?>("IssuedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("issued_at");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("policy_number");

                    b.Property<decimal>("Premium")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("premium");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("quote_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.HasKey("PolicyId")
                        .HasName("pk_policies");

                    b.HasIndex("ExternalReferenceId")
                        .IsUnique()
                        .HasDatabaseName("ix_policies_external_reference_id");

                    b.HasIndex("PolicyNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_policies_policy_number");

                    b.HasIndex("QuoteId")
                        .IsUnique()
                        .HasDatabaseName("ix_policies_quote_id");

                    b.ToTable("policies");
                });

            modelBuilder.Entity("EOQuoter.Data.Entities.ProcessedMessageRow", b =>
                {
                    b.Property<string>("DedupeKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("dedupe_key");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("processed_at");

                    b.HasKey("DedupeKey")
                        .HasName("pk_processed_messages");

                    b.ToTable("processed_messages");
                });

            modelBuilder.Entity("EOQuoter.Data.Entities.QuoteRow", b =>
                {
                    b.Property<Guid>("QuoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("quote_id");

                    b.Property<decimal>("BasePremium")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("base_premium");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("ExpiresOn")
                        .HasColumnType("date")
                        .HasColumnName("expires_on");

                    b.Property<string>("LedgerJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ledger_json");

                    b.Property<decimal>("Limit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("limit");

                    b.Property<decimal>("Premium")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("premium");

                    b.Property<DateOnly>("QuoteDate")
                        .HasColumnType("date")
                        .HasColumnName("quote_date");

                    b.Property<DateOnly>("RateEffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("rate_effective_date");

                    b.Property<decimal>("Retention")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("retention");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.Property<string>("SubjectivitiesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("subjectivities_json");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("submission_id");

                    b.HasKey("QuoteId")
                        .HasName("pk_quotes");

                    b.HasIndex("SubmissionId")
                        .HasDatabaseName("ix_quotes_submission_id");

                    b.ToTable("quotes");
                });

            modelBuilder.Entity("EOQuoter.Data.Entities.RateRow", b =>
                {
                    b.Property<int>("ProfessionClass")
                        .HasColumnType("int")
                        .HasColumnName("profession_class");

                    b.Property<int>("RevenueBand")
                        .HasColumnType("int")
                        .HasColumnName("revenue_band");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<decimal>("BaseRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("base_rate");

                    b.HasKey("ProfessionClass", "RevenueBand", "EffectiveDate")
                        .HasName("pk_rate_table");

                    b.ToTable("rate_table", (string)null);
                });

            modelBuilder.Entity("EOQuoter.Data.Entities.RecencyBandRow", b =>
                {
                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<string>("Label")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("label");

                    b.Property<double>("AgeCeilingExclusiveYears")
                        .HasColumnType("float")
                        .HasColumnName("age_ceiling_exclusive_years");

                    b.Property<double>("AgeFloorInclusiveYears")
                        .HasColumnType("float")
                        .HasColumnName("age_floor_inclusive_years");

                    b.Property<decimal>("Weight")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("weight");

                    b.HasKey("EffectiveDate", "Label")
                        .HasName("pk_recency_bands");

                    b.ToTable("recency_bands");
                });

            modelBuilder.Entity("EOQuoter.Data.Entities.ReconciliationResultRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("batch_id");

                    b.Property<decimal?>("CarrierGross")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("carrier_gross");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detail");

                    b.Property<string>("ExternalReferenceId")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("external_reference_id");

                    b.Property<decimal?>("MgaGross")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("mga_gross");

                    b.Property<DateOnly>("Period")
                        .HasColumnType("date")
                        .HasColumnName("period");

                    b.HasKey("Id")
                        .HasName("pk_reconciliation_results");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_reconciliation_results_batch_id");

                    b.ToTable("reconciliation_results");
                });

            modelBuilder.Entity("EOQuoter.Data.Entities.RejectedItemRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("batch_id");

                    b.Property<string>("ExternalReferenceId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("external_reference_id");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("raw_payload");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("RejectedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("rejected_at");

                    b.Property<Guid>("RejectsRef")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("rejects_ref");

                    b.Property<DateTimeOffset?>("ReprocessedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("reprocessed_at");

                    b.HasKey("Id")
                        .HasName("pk_rejected_items");

                    b.HasIndex("RejectsRef")
                        .HasDatabaseName("ix_rejected_items_rejects_ref");

                    b.ToTable("rejected_items");
                });

            modelBuilder.Entity("EOQuoter.Data.Entities.RetentionFactorRow", b =>
                {
                    b.Property<decimal>("RetentionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("retention_amount");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<decimal>("Factor")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("factor");

                    b.HasKey("RetentionAmount", "EffectiveDate")
                        .HasName("pk_retention_factors");

                    b.ToTable("retention_factors");
                });

            modelBuilder.Entity("EOQuoter.Data.Entities.SeverityBandRow", b =>
                {
                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<string>("Label")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("label");

                    b.Property<decimal?>("CeilingExclusive")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ceiling_exclusive");

                    b.Property<decimal>("FloorInclusive")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("floor_inclusive");

                    b.Property<decimal>("Load")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("load");

                    b.HasKey("EffectiveDate", "Label")
                        .HasName("pk_severity_bands");

                    b.ToTable("severity_bands");
                });

            modelBuilder.Entity("EOQuoter.Data.Entities.SubmissionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("content_type");

                    b.Property<Guid?>("QuoteId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("quote_id");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("raw_content");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("received_at");

                    b.Property<string>("ReferralReason")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("referral_reason");

                    b.Property<string>("RiskProfileJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("risk_profile_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_submissions");

                    b.ToTable("submissions");
                });

            modelBuilder.Entity("EOQuoter.Data.Entities.UnderwritingParameterRow", b =>
                {
                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<int>("ClaimsKnockoutCount")
                        .HasColumnType("int")
                        .HasColumnName("claims_knockout_count");

                    b.Property<int>("ClaimsWindowYears")
                        .HasColumnType("int")
                        .HasColumnName("claims_window_years");

                    b.Property<int>("MinYearsInBusiness")
                        .HasColumnType("int")
                        .HasColumnName("min_years_in_business");

                    b.HasKey("EffectiveDate")
                        .HasName("pk_underwriting_parameters");

                    b.ToTable("underwriting_parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
